package Views;

import Models.Rider;
import Models.Rider.Record;
import Controllers.RiderController;
import javax.swing.JOptionPane;

public class RiderView extends javax.swing.JFrame {

    Rider objRider;
    Record objRecord;
    RiderController objController;

    public RiderView() {
        initComponents();
        objController = new RiderController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        txtMedals = new javax.swing.JTextField();
        txtSpeed = new javax.swing.JTextField();
        txtRecords = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        btnBMI = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnAddRider = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rider System 1.1");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("National Records:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 172, -1, 35));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Weight:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 97, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Country:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 97, 35));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Age:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 97, 35));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Height:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 97, 35));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Name:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 85, 97, 35));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Olympic Medals:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 85, -1, 35));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Top Speed:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 131, 129, 35));
        jPanel2.add(txtCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 178, -1));
        jPanel2.add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 178, -1));
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 95, 178, -1));
        jPanel2.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 180, -1));

        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });
        jPanel2.add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 178, -1));
        jPanel2.add(txtMedals, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 95, 127, -1));

        txtSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpeedActionPerformed(evt);
            }
        });
        jPanel2.add(txtSpeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 141, 127, -1));

        txtRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecordsActionPerformed(evt);
            }
        });
        jPanel2.add(txtRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 182, 127, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Search Rider By Name:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 276, 166, 40));
        jPanel2.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 184, -1));

        btnBMI.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBMI.setText("Calculate BMI");
        btnBMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBMIActionPerformed(evt);
            }
        });
        jPanel2.add(btnBMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 220, 160, 40));

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 270, 150, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setText("Rider System");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 11, 270, -1));

        btnAddRider.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddRider.setText("Add Rider");
        btnAddRider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRiderActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddRider, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 142, 40));

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        jPanel2.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 120, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightActionPerformed

    private void txtRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecordsActionPerformed

    private void btnBMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBMIActionPerformed
        float weight = Float.parseFloat(txtWeight.getText());
        float height = Float.parseFloat(txtHeight.getText());

        double bmi = objRider.calBMI(weight, height);
        JOptionPane.showMessageDialog(rootPane, "BMI value is " + bmi, "BMI", 1);
    }//GEN-LAST:event_btnBMIActionPerformed

    private void btnAddRiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRiderActionPerformed
        String name = txtName.getText();
        int age = Integer.parseInt(txtAge.getText());
        String country = txtCountry.getText();
        float weight = Float.parseFloat(txtWeight.getText());
        float height = Float.parseFloat(txtHeight.getText());
        int medols = Integer.parseInt(txtMedals.getText());
        int records = Integer.parseInt(txtRecords.getText());
        float speed = Float.parseFloat(txtSpeed.getText());

        objRider = objController.addRider(name, country, age, weight, height);
        objRecord = objController.addRiderRecord(medols, speed, records);

        JOptionPane.showMessageDialog(rootPane, "Data added sussucfully !", "Sucess", 1);


    }//GEN-LAST:event_btnAddRiderActionPerformed

    private void txtSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpeedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpeedActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtAge.setText("");
        txtCountry.setText("");
        txtHeight.setText("");
        txtMedals.setText("");
        txtName.setText("");
        txtSpeed.setText("");
        txtRecords.setText("");
        txtWeight.setText("");
        txtsearch.setText("");

    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RiderView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRider;
    private javax.swing.JButton btnBMI;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtMedals;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRecords;
    private javax.swing.JTextField txtSpeed;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
